### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/data/private/voice/LJSpeech-1.0/transcript.csv'

### ISSUE THREAD

**Issue by Waguitar** [Kyubyong/tacotron#130]
I made the directory data = "/data/private/voice/LJSpeech-1.0" form hyperparams.py . I have the transcript.csv in these directory "/data/private/voice/LJSpeech-1.0" yet when I run python prepro.py I am getting these error and yet I still have the transcript.csv in that folder.What could be the problem.I have set prepro True`.Why these error yet I have these directory and the transcript.csv. Infact I have also tried to put metadata.csv from the original file. It has not worked for me for 2 days. These is the error
```
Traceback (most recent call last):
  File "prepro.py", line 17, in <module>
    fpaths, _, _ = load_data() # list
  File "/home/rutherford/Speech/tacotron-master/data_load.py", line 41, in load_data
    lines = codecs.open(transcript, 'r', 'utf-8').readlines()
  File "/usr/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '/data/private/voice/LJSpeech-1.0/transcript.csv'
```

**Comment by heidenrei** [comment]
Are you sure that the path for the transcript file is correct?
