### ISSUE TITLE
Error executing train.py

### ISSUE THREAD

**Issue by arunbaby0** [Kyubyong/tacotron#2]
I am getting an error when I execute train.py

`Traceback (most recent call last):
  File "train.py", line 277, in <module>
    main()
  File "train.py", line 255, in main
    g = Graph(is_training=True); print("Training Graph loaded")
  File "train.py", line 234, in __init__
    self.memory = encode(self.x, is_training=is_training)
  File "/SpeakerID-IIT/tts/voices/taco/tacotron-master/networks.py", line 47, in encode
    memory = gru(enc, hp.embed_size//2, True) # (N, T, 128*2)
  File "/SpeakerID-IIT/tts/voices/taco/tacotron-master/modules.py", line 103, in gru
    outputs, _ = tf.nn.bidirectional_dynamic_rnn(cell, cell_bw, inputs, dtype=tf.float32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 363, in bidirectional_dynamic_rnn
    seq_dim=time_dim, batch_dim=batch_dim)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 2346, in reverse_sequence
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2776, in reverse_sequence
    batch_dim=batch_dim, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 504, in apply_op
    values, as_ref=input_arg.is_ref).dtype.name
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 360, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
`

**Comment by marcossilva** [comment]
It's working here for me. Which tensorflow version do you have installed?

**Comment by basuam** [comment]
@arunbaby0 : It is working for me too.
I'm not an expert but I agree with @marcossilva , check that you really comply with the  "Requirements".

**Comment by arunbaby0** [comment]
I am using tensorflow version 1.0. And I installed all the requirments.

**Comment by Durham** [comment]
This may be related issue https://stackoverflow.com/questions/39808336/tensorflow-bidirectional-dynamic-rnn-none-values-error

I installed latest tensorflow 1.1 specifically for trying this code, before upgrading I had various issues (although not this one). I think you should try upgrading to tensorflow 1.1. and see if it helps.

**Comment by basuam** [comment]
@arunbaby0
Did you solve your problem? If so, can you close this issue?
Thank you for your help.

**Comment by arunbaby0** [comment]
@Durham Thanks a lot. It started working after I upgraded to 1.1.0.
I think it's better to update the requirements to TF 1.1 in the requirements section.
