### ISSUE TITLE
Python train.py gives me ValueError: None values not supported

### ISSUE THREAD

**Issue by joji7** [Kyubyong/tacotron#27]
Hi, I'm facing this issue since past two days trying to run the program. I'm running it on Ubuntu 16.04 with Nvidia 965m. 
I have tried following ways:
Used both Python 2.7 and Python 3
Used tensorflow version 1.0.0.

Could you please help me resolve the issue? Here is my complete output:

`Tensor("encoder/highwaynet_3/add:0", shape=(32, ?, 128), dtype=float32)
Traceback (most recent call last):
  File "train.py", line 93, in <module>
    main()
  File "train.py", line 73, in main
    g = Graph(); print("Training Graph loaded")
  File "train.py", line 37, in __init__
    self.memory = encode(self.x, is_training=is_training) # (N, T, E)
  File "/home/user/tacotron/networks.py", line 57, in encode
    memory = gru(enc, hp.embed_size//2, True) # (N, T, E)
  File "/home/user/tacotron/modules.py", line 209, in gru
    outputs, _ = tf.nn.bidirectional_dynamic_rnn(cell, cell_bw, inputs, dtype=tf.float32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 363, in bidirectional_dynamic_rnn
    seq_dim=time_dim, batch_dim=batch_dim)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 2346, in reverse_sequence
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2776, in reverse_sequence
    batch_dim=batch_dim, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 504, in apply_op
    values, as_ref=input_arg.is_ref).dtype.name
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 360, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.`

Thanks in advance

**Comment by candlewill** [comment]
Try to update your TensorFlow version to v1.1.

**Comment by joji7** [comment]
Thanks for the help,  I tried the exact version of tensorflow@1.1.0, but the program stuck at progress bar, repeated three times. Can you tell me what could cause this problem?
Here is the output
python train_multi_gpus.py 
Training Graph loaded
2017-06-06 20:29:03.743174: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-06 20:29:03.743204: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-06 20:29:03.743209: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-06 20:29:03.743222: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-06 20:29:03.743229: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-06-06 20:29:03.951710: E tensorflow/stream_executor/cuda/cuda_driver.cc:405] failed call to cuInit: CUDA_ERROR_UNKNOWN
2017-06-06 20:29:03.951749: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: srinivas-Alienbot
2017-06-06 20:29:03.951761: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: srinivas-Alienbot
2017-06-06 20:29:03.951786: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 375.66.0
2017-06-06 20:29:03.951808: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  375.66  Mon May  1 15:29:16 PDT 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
"""
2017-06-06 20:29:03.951823: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 375.66.0
2017-06-06 20:29:03.951829: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 375.66.0
  0%|                                          | 0/152 [00:00<?, ?b/s]    

  1%|▏                                 | 1/152 [00:14<37:18, 14.82s/b]
 10%|███▎                             | 15/152 [02:36<21:13,  9.30s/b]
 11%|███▋                             | 17/152 [02:57<22:17,  9.91s/b]

**Comment by YisenWang** [comment]
I am using the tensorflow 1.10. And when I run train.py, it can work. But when I run train_multi_gpus.py, it report None value error. Do someone know the reason? Thanks!

**Comment by joji7** [comment]
@YisenWang Try to remove tensorflow and install tensorflow-gpu==1.1. I solved None value error by doing that
