### ISSUE TITLE
Another implementation of tacotron, has anyone tried it ?

### ISSUE THREAD

**Issue by huguanglong** [Kyubyong/tacotron#41]
There is another implementation of tacotron, has anyone tried it ? [https://github.com/barronalex/Tacotron](url)

**Comment by candlewill** [comment]
More choice is always better. I will try it later. Thanks for your sharing.

**Comment by YisenWang** [comment]
@candlewill how is the performance?

**Comment by Durham** [comment]
Alternative implementation works as well (tried it on relatively small dataset of single words, and it can be trained to say them and new words also). In my opinion implementation in this repository, as opposed to https://github.com/barronalex/Tacotron is much better structured and clean, but https://github.com/barronalex/Tacotron works a bit better (but I didn't try it with latest changes). One thing that I found very convenient there, is that it saves evaluation results (new and original speech + alignment) every nth step. This simplified monitoring and allowed me to find a problem with my dataset (audiofiles were corrupted after conversion to spectrogram and back, I think because wav header specified incorrect frame rate). I'm going to run comparison of both implementations on larger dataset soon.

**Comment by YisenWang** [comment]
@Durham Have you run into the following issues? using the code https://github.com/barronalex/Tacotron

Traceback (most recent call last):
File "train.py", line 117, in 
train(model, config)
File "train.py", line 28, in train
batch_inputs = data_input.build_dataset(sess, inputs)
File "/data1/home/yisenwang/TTS/tacotron2/Tacotron/data_input.py", line 26, in build_dataset
dataset = tf.contrib.data.Dataset.from_tensor_slices(placeholders)
File "/data1/home/yisenwang/TTS/tacotron2/Tacotron/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 473, in from_tensor_slices
return TensorSliceDataset(tensors)
File "/data1/home/yisenwang/TTS/tacotron2/Tacotron/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 907, in init
for i, t in enumerate(nest.flatten(tensors))
File "/data1/home/yisenwang/TTS/tacotron2/Tacotron/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 610, in convert_to_tensor
as_ref=False)
File "/data1/home/yisenwang/TTS/tacotron2/Tacotron/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 675, in internal_convert_to_tensor
ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
File "/data1/home/yisenwang/TTS/tacotron2/Tacotron/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 921, in _autopacking_conversion_function
return _autopacking_helper(v, inferred_dtype, name or "packed")
File "/data1/home/yisenwang/TTS/tacotron2/Tacotron/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 863, in _autopacking_helper
"%s to %s (Tensor is: %r)" % (elem.dtype, dtype, elem))
TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'float32'> to <dtype: 'int32'> (Tensor is: <tf.Tensor 'Placeholder_2:0' shape=(1131, 64, 5125) dtype=float32>)

**Comment by diegor8** [comment]
the project is now gone

**Comment by GuangChen2016** [comment]
@Durham Hello, Durham.  Are you still working on this? I still couldn't got good results, and the alignment seemed didn't work according to the alignment pictures. Do you have some samples of of this two different implementation? and could you provide some samples? Thank you very much.
