### ISSUE TITLE
Error in running eval.py

### ISSUE THREAD

**Issue by zuoxiang95** [Kyubyong/tacotron#61]
I have trained a single person's speech. when i run python eval.py, i get this error:

Traceback (most recent call last):
  File "eval.py", line 70, in <module>
    eval()
  File "eval.py", line 39, in eval
    sv.saver.restore(sess, tf.train.latest_checkpoint(hp.logdir))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key net/encoder/norm2/Variable not found in checkpoint
	 [[Node: save/RestoreV2_117 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_117/tensor_names, save/RestoreV2_117/shape_and_slices)]]
	 [[Node: save/RestoreV2_71/_453 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_442_save/RestoreV2_71", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by keicoon** [comment]
``` tensorflow.python.framework.errors_impl.NotFoundError: Key net/encoder/norm2/Variable not found in checkpoint ```
I think your project having empty checkpoint.
Check your `hyperprams.py` `logdir` path. This path must have tensorflow checkpoint files.

**Comment by sniperwrb** [comment]
same problem here.

If you trained and evaled with different norm_type, it will happen.
Sometimes training with norm_type="ins" does not work, in that case it would happen too.
