### ISSUE TITLE
Error running eval.py

### ISSUE THREAD

**Issue by hoonyoung** [Kyubyong/tacotron#68]
I have trained the model with full set (bible) DB and I got model_epoch_40_gs_80000.* files in "logdir_s" directory.   When I tried with eval.py I got the following "Size mismatch between n_fft and window size" error.

Anybody experienced the similar problem? 

$ python eval.py
...
2017-07-11 19:29:59.842658: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
WARNING:tensorflow:Standard services need a 'logdir' passed to the SessionManager
Restored!
Traceback (most recent call last):
  File "eval.py", line 69, in <module>
    eval()
  File "eval.py", line 62, in eval
    audio = spectrogram2wav(np.power(np.e, s)**hp.power)
  File "/home/abc/Tacotron/tacotron/utils.py", line 93, in spectrogram2wav
    X_t = invert_spectrogram(X_best)
  File "/home/abc/Tacotron/tacotron/utils.py", line 105, in invert_spectrogram
    return librosa.istft(spectrogram, hp.hop_length, win_length=hp.win_length, window="hann")
  File "/usr/local/lib/python2.7/dist-packages/librosa/core/spectrum.py", line 294, in istft
    raise ParameterError('Size mismatch between n_fft and window size')
librosa.util.exceptions.ParameterError: Size mismatch between n_fft and window size

**Comment by hoonyoung** [comment]
Just noticed that this issue was addressed in the past, so I'll close it.
