### ISSUE TITLE
How do I use my own training data?

### ISSUE THREAD

**Issue by thuoctran** [Kyubyong/tacotron#75]
Hi everyone,

I've try to reduce the training dataset just only 1 folder, in my case in Genesis. I also changed the csv file, so that's only texts for the Genesis folder. But when I run the train.py, I got this problem.

Genesis/Genesis_1-1
Traceback (most recent call last):
  File "train.py", line 128, in <module>
    main()
  File "train.py", line 108, in main
    g = Graph(); print("Training Graph loaded")
  File "train.py", line 35, in __init__
    self.x, self.y, self.z, self.num_batch = get_batch()
  File "/Users/thuoctran/Desktop/Projects/Tacotron/tacotron/data_load.py", line 125, in get_batch
    texts, sound_files = load_train_data() # byte, string
  File "/Users/thuoctran/Desktop/Projects/Tacotron/tacotron/prepro.py", line 45, in load_train_data
    texts, sound_files = create_train_data()
  File "/Users/thuoctran/Desktop/Projects/Tacotron/tacotron/prepro.py", line 33, in create_train_data
    sound_fname, text, duration = row
ValueError: need more than 1 value to unpack

I'm using python 2.7. Can anyone help me to solve it?

Thank you in advance :)

**Comment by zuoxiang95** [comment]
Do you edit batch_size to 1?

**Comment by thuoctran** [comment]
do you mean I should change the batch_size = 1 in a hyperparams.py file?

**Comment by zuoxiang95** [comment]
yes

**Comment by thuoctran** [comment]
Well, I've tried to use my own samples. They're test_1 - test_3, and I also modified a text.csv into my own texts. I did changed a batch_size = 3 in a hyperparams.py file according to your advice. The files in my logdir_s folder is totally strange. They named such as mode_epoch_40_gs_0.index, and a checkpoint file is in text format (from Kyubuyong, his pretrain checkpoint format is unix executable).
But there's no error when I run train.py file. 
Beside that, when I run eval.py, an error occurs (Floating point exception: 8).

**Comment by zuoxiang95** [comment]
You should adjust the "min_len" and "max_len" in hyperparams.py to make sure that your data can be fed into training process.

**Comment by thuoctran** [comment]
the length of text is is from 25 to 75, so I think I don't need to change them. But why's my global steps (gs = 0) according to saved files in logdir?

**Comment by yisiliu** [comment]
You need to store your text in a csv file, in which each line is filename(without .wav), the transcript, duration(number of milliseconds). This error is shown in line **sound_fname, text, duration = row**

**Comment by RobinsonSir** [comment]
Anyone use chinese speech data? how to use it? [http://www.openslr.org/18/](http://www.openslr.org/18/)
