### ISSUE TITLE
No such file or directory: 'WEB/text.csv'

### ISSUE THREAD

**Issue by iamcaochong** [Kyubyong/tacotron#90]
`Traceback (most recent call last):
  File "F:\tts\tacotron\tacotron-master\train_multi_gpus.py", line 137, in <module>
    main()
  File "F:\tts\tacotron\tacotron-master\train_multi_gpus.py", line 117, in main
    g = Graph(); print("Training Graph loaded")
  File "F:\tts\tacotron\tacotron-master\train_multi_gpus.py", line 31, in __init__
    self.x, self.y, self.z, self.num_batch = get_batch()
  File "F:\tts\tacotron\tacotron-master\data_load.py", line 125, in get_batch
    texts, sound_files = load_train_data() # byte, string
  File "F:\tts\tacotron\tacotron-master\prepro.py", line 43, in load_train_data
    texts, sound_files = create_train_data()
  File "F:\tts\tacotron\tacotron-master\prepro.py", line 29, in create_train_data
    reader = csv.reader(codecs.open(hp.text_file, 'rb', 'utf-8'))
  File "C:\Python35\lib\codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'WEB/text.csv'`

**Comment by StanDex** [comment]
Have you resolved this problem? I have similar now

**Comment by StanDex** [comment]
You should download a "WEB" folder and a file "text.csv" - review the Kyubyong instructions

**Comment by 18810319795** [comment]
@iamcaochong  Hello , can you tell me where  i  can download "text.csv"?

**Comment by JasonMFry** [comment]
In [README.md](https://github.com/Kyubyong/tacotron/blob/master/README.md), the author links to the [World English Bible](https://www.kaggle.com/bryanpark/the-world-english-bible-speech-dataset). If you download that audio Bible, it will contain `text.csv`.
