### ISSUE TITLE
AttributeError: 'module' object has no attribute 'BahdanauAttention'

### ISSUE THREAD

**Issue by Shirley-Ji** [Kyubyong/tacotron#96]
Hey guys, 

I cloned the code to my local machine and run train.py without any problems, but I hit this error when deploying tacotron to Google cloud, I am not sure what happened here. It's very appreciated for your suggestions.

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/.local/lib/python2.7/site-packages/tacotron/train.py", line 169, in <module>
    main()
  File "/root/.local/lib/python2.7/site-packages/tacotron/train.py", line 109, in main
    g = Graph(); print("Training Graph loaded")
  File "/root/.local/lib/python2.7/site-packages/tacotron/train.py", line 50, in __init__
    is_training=is_training) # (N, T', hp.n_mels*hp.r)
  File "/root/.local/lib/python2.7/site-packages/tacotron/networks.py", line 85, in decode1
    dec = attention_decoder(dec, memory, num_units=hp.embed_size) # (N, T', E)
  File "/root/.local/lib/python2.7/site-packages/tacotron/modules.py", line 246, in attention_decoder
    attention_mechanism = tf.contrib.seq2seq.BahdanauAttention(num_units,
AttributeError: 'module' object has no attribute 'BahdanauAttention'

**Comment by wotulong** [comment]
Is the service does not have 'tf.contrib' model? Just guessing.

**Comment by Shirley-Ji** [comment]
Good suggestion. I've tried and found Google cloud set tf=1.0 by default, I changed it version to be >1.4 in setup.py, then didn't hit this error so far. Thanks very much.
